
Running model pipeline for data fold 3...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'lung_side', 'de_stag', 'de_stag_7thed', 'sct_slice_new', 'sct_nod_err']
Error executing job with overrides: []
Traceback (most recent call last):
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 54, in run_hyperparameter_grid_based_execution_pipeline
    run_experiment_pipeline(config)
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 149, in run_experiment_pipeline
    model_pipeline = ModelPipeline(
                     ^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/model_pipeline.py", line 33, in __init__
    self.pytorch_lightning_model = PyTorchLightningModel(
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/pytorch_lightning_model.py", line 36, in __new__
    return PyTorchLightningResNet182dModel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/resnet182d/pytorch_lightning_resnet18_2d_model_oneclass.py", line 18, in __init__
    self.criterion = ResNet50LossFunction(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/loss_functions/resnet50_loss_functions.py", line 11, in __init__
    self.weights = self._get_label_weights(experiment_execution_paths)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/loss_functions/resnet50_loss_functions.py", line 33, in _get_label_weights
    metadataframe = MetadataFrame(
                    ^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/data/metadataframe/metadataframe.py", line 23, in __new__
    return NLSTPreprocessedMetaDataFrame(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/data/metadataframe/preprocessed_metadataframes/nlst_metadataframe.py", line 18, in __init__
    self._save_metadataframe_as_csv(
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/data/metadataframe/preprocessed_metadataframes/nlst_metadataframe.py", line 59, in _save_metadataframe_as_csv
    self.lung_metadataframe.to_csv(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pandas/io/common.py", line 157, in __exit__
    self.close()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pandas/io/common.py", line 144, in close
    handle.close()
OSError: [Errno 122] Disk quota exceeded

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
